Vagrant.configure("2") do |config|
  config.vm.box = "basic"

  config.vm.define :z1a do |z1a|
    z1a.vm.provider :google do |google|
      google.zone = "europe-west1-c"

      google.zone_config "europe-west1-c" do |z1a_zone|
        z1a_zone.name = "vagrant-acceptance-multi-z1a-#{('a'..'z').to_a.sample(8).join}"
        z1a_zone.machine_type = "n1-standard-1"
        z1a_zone.disk_type = "pd-ssd"
      end
    end
  end

  config.vm.define :z1b do |z1b|
    z1b.vm.provider :google do |google|
      google.zone = "europe-west1-d"

      google.zone_config "europe-west1-d" do |z1b_zone|
        z1b_zone.name = "vagrant-testing-acceptance-multi-z1b-#{('a'..'z').to_a.sample(8).join}"
        z1b_zone.machine_type = "n1-standard-2"
        z1b_zone.disk_type = "pd-ssd"
      end
    end
  end
end
