Vagrant.configure("2") do |config|
  config.vm.box = "basic"

  config.vm.provider :google do |google|

    google.zone = "europe-west1-d"

    google.zone_config "europe-west1-d" do |zone1d|
      zone1d.name = "vagrant-acceptance-instance-groups-#{('a'..'z').to_a.sample(8).join}"
      zone1d.instance_group = "vagrant-acceptance-#{('a'..'z').to_a.sample(8).join}"
      zone1d.disk_type = "pd-ssd"
    end
  end
end
