Vagrant.configure("2") do |config|
  config.vm.box = "basic"

  config.vm.provider :google do |google|

    google.zone = "australia-southeast1-b"

    google.zone_config "australia-southeast1-b" do |zone|
      zone.name = "vagrant-acceptance-instance-groups-#{('a'..'z').to_a.sample(8).join}"
      zone.instance_group = "vagrant-acceptance-#{('a'..'z').to_a.sample(8).join}"
      zone.disk_type = "pd-ssd"
      zone.image_family = "debian-9"
    end
  end
end
