# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :google do |google|
    google.image = "debian-7-v20130522"
    google.machine_type = "n1-standard-1"
    google.zone = "us-central1-a"
  end
end
