Vagrant.configure("2") do |config|
  config.vm.box = "basic"

  config.vm.provider :google do |google|

    google.zone = "australia-southeast1-b"

    google.zone_config "australia-southeast1-b" do |zone|
      zone.name = "vagrant-acceptance-preemptible-#{('a'..'z').to_a.sample(8).join}"
      zone.disk_type = "pd-ssd"
      zone.preemptible = true
      zone.auto_restart = false
      zone.on_host_maintenance = "TERMINATE"
      zone.image_family = "debian-9"
    end
  end
end
