Vagrant.configure("2") do |config|
  config.vm.box = "basic"

  config.vm.provider :google do |google, override|

    google.zone = "europe-west1-d"

    google.zone_config "europe-west1-d" do |zone1d|
        zone1d.name = "vagrant-testing-preemptible"
        zone1d.image = "debian-7-wheezy-v20150603"
        zone1d.zone = "europe-west1-d"
        zone1d.preemptible = true
        zone1d.auto_restart = false
        zone1d.on_host_maintenance = "TERMINATE"
    end
  end
end