Vagrant.configure("2") do |config|
  config.vm.box = "basic"

  config.vm.provider :google do |google|

    google.zone = "europe-west1-d"

    google.zone_config "europe-west1-d" do |zone1d|
      zone1d.name = "vagrant-acceptance-scopes"
      zone1d.scopes = ['sql-admin',
                       'bigquery',
                       'https://www.googleapis.com/auth/compute'
                      ]
      zone1d.disk_type = "pd-ssd"
    end
  end
end
